[package]
name = "oas_gen"
version = "0.1.1-alpha.0"
authors = ["Andras Mocsary <nobody@reedwolf.com>"]
repository = "https://gitlab.com/reed-wolf/oas_gen"
documentation = "https://docs.rs/oas_gen/"
license = "MIT OR Apache-2.0"

edition = "2018"
publish = true

[dependencies]
schemars = "0.6.5"
serde = "1.0.104"
serde_json = "1.0.44"
http = "0.2.0"
heck = "0.3.1"
contracts = "0.3.0"

[dev-dependencies]
schemars_derive = "0.6.5"
openapiv3 = "0.3.0"

[features]
# no features by default
default = []
teapot = []
