[package]
name = "oas_gen"
version = "0.1.0"
authors = ["Andras Mocsary <nobody@reedwolf.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
schemars = "0.6.5"
serde = "1.0.104"
serde_json = "1.0.44"
http = "0.2.0"

[dev-dependencies]
schemars_derive = "0.6.5"
openapiv3 = "0.3.0"
